### ISSUE TITLE
mock-data的路径写错了

### ISSUE THREAD

**Issue by AnonymousArthur** [DevUIStudy/devui-study-101-Xihoo-PKU#1]
https://github.com/DevUIStudy/devui-study-101-Xihoo-PKU/blob/950a19ccc6fa37d86b88188f0301df410e022fe0/src/app/admin-files-chart/admin-files-chart.component.ts#L2
应该为` import { SourceType, originSource } from './mock-data.ts'; `

**Comment by HhooX** [comment]
> https://github.com/DevUIStudy/devui-study-101-Xihoo-PKU/blob/950a19ccc6fa37d86b88188f0301df410e022fe0/src/app/admin-files-chart/admin-files-chart.component.ts#L2
> 
> 
> 应该为`import { SourceType, originSource } from './mock-data.ts';`

收到
